services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: qwerty
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blog_user -d blog_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "django-insecure-bpr13-17f#rei=7gv)zp)ik=b0swqhi4a5defv#j*uk#i2(dq)"
      DB_HOST: db
      DB_PASSWORD: qwerty
      DEBUG: "True"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
